### ISSUE TITLE
nodeFlags: v8flags.fetch()

### ISSUE THREAD

**Issue by petersiman** [liferay/liferay-theme-tasks#9]
Hi, maybe it's gulp issue, but when using gulp@3.8.10, the `gulp build` tasks fails with following error: 

```shell
C:\Users\User1\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:25
  nodeFlags: v8flags.fetch()
                     ^
TypeError: undefined is not a function
    at Object.<anonymous> (C:\Users\User1\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Downgrade to gulp@3.8.8 resolves this problem.

**Comment by Robert-Frampton** [comment]
Looks like an issue with that version of gulp https://github.com/gulpjs/gulp/issues/810, upgrading to a newer version should also resolve the issue.
